name: Build and publish retroarch-uwp Docker image

on:
  push:
    branches: [ main ]

jobs:

  build:

    # The Dockerfile must run on the same OS version as it builds
    # so lock this version down. If this needs to change, I also
    # need to change the FROM image in the Dockerfiles
    runs-on: windows-2019

    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        # The official Docker build-push-action doesn't support Windows:
        # https://github.com/docker/build-push-action/issues/18
        name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: silentj/libretro-docker
          tags: latest
          registry: docker.io
          directory: retroarch-uwp
          dockerfile: retroarch-uwp/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
