name: Build and publish retroarch-uwp Docker image

on:
  push:
    branches: [ main ]

jobs:

  build:

    # The Dockerfile must run on the same OS version as it builds
    # so lock this version down. If this needs to change, I also
    # need to change the FROM image in the Dockerfiles
    runs-on: windows-2019

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --tag retroarch-uwp:$(date +%s) retroarch-uwp
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: silentj/libretro-docker
          tag_with_ref: true